language: cpp
compiler: gcc
services:
  - docker
install:
  - sudo apt-get update -qq
before_script:
  - docker build -t facebook/proxygen .
script:
  - docker run -ti facebook/proxygen
addons:
  apt:
    packages:
    - g++-4.9
    - gcc-4.9
