sudo: required

services:
  - docker

matrix:
  include:
    - env: [ubuntu_version=14.04, gcc_version=4.9]
    - env: [ubuntu_version=16.04, gcc_version=5.4]

script:
  # Travis seems to get confused when `matrix:` is used with `language:`
  - sudo apt-get install python2.7
  # We don't want to write this script inline because of a Travis bug --
  # it looks like it escapes " and \ in scripts when using `matrix:`.
  - ./travis-emit-dockerfile.sh
  - docker build .
